const SB_URL='https://ozsfnvzqtizptxymtxzf.supabase.co';
const SB_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96c2ZudnpxdGl6cHR4eW10eHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEwNjIzMjksImV4cCI6MjEwNjYzODMyOX0.2TuFxRzKL4aHjRsFNyVsG3-LPn4UGre64NzhnT7W1Po';
const API=SB_URL+'/rest/v1', AUTH=SB_URL+'/auth/v1'; const $=id=>document.getElementById(id);
let session=null, products=[], selectedSmall='', selectedLarge='', currentProductImage='';
const DEFAULTS={brand:'Witama Store.ID'};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function ls(k,v){try{if(v===undefined)return localStorage.getItem(k);if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,v);}catch{return null;}}
function headers(token=null){return {apikey:SB_ANON_KEY,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})};}
async function fetchT(url,opts={},ms=18000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...opts,signal:c.signal});}catch(e){if(e.name==='AbortError')throw new Error('Koneksi Supabase timeout. Cek internet/project Supabase.');throw new Error('Tidak bisa terhubung ke Supabase. '+(e.message||''));}finally{clearTimeout(t);}}
async function errorText(r){let b={};try{b=await r.json();}catch{}const raw=b.msg||b.message||b.error_description||b.details||'';if(/invalid login credentials/i.test(raw))return'Email atau password salah.';if(/email.*not.*confirm/i.test(raw))return'Email belum dikonfirmasi di Supabase Authentication.';if(/api key/i.test(raw))return'API key Supabase tidak valid.';return raw||'HTTP '+r.status;}
async function authLogin(email,password){const r=await fetchT(AUTH+'/token?grant_type=password',{method:'POST',headers:headers(),body:JSON.stringify({email,password})});if(!r.ok)throw new Error(await errorText(r));return r.json();}
async function authUser(token){const r=await fetchT(AUTH+'/user',{headers:{apikey:SB_ANON_KEY,Authorization:'Bearer '+token}});if(!r.ok)throw new Error(await errorText(r));return r.json();}
async function authRefresh(refresh_token){const r=await fetchT(AUTH+'/token?grant_type=refresh_token',{method:'POST',headers:headers(),body:JSON.stringify({refresh_token})});if(!r.ok)throw new Error(await errorText(r));return r.json();}
function saveSession(s){session=s;ls('witama_admin_session',JSON.stringify(s));if(s?.user?.email)ls('witama_admin_email',s.user.email);}
async function restoreSession(){const raw=ls('witama_admin_session');if(!raw)return false;try{const s=JSON.parse(raw);await authUser(s.access_token);session=s;return true;}catch{try{const s=JSON.parse(raw);if(!s.refresh_token)throw 0;saveSession(await authRefresh(s.refresh_token));return true;}catch{ls('witama_admin_session',null);return false;}}}
async function db(path,opts={}){const r=await fetchT(API+path,{...opts,headers:{...headers(session?.access_token),...(opts.headers||{})}});if(!r.ok)throw new Error(await errorText(r));if(r.status===204)return null;return r.json();}
function notice(msg,error=false){const e=$('notice');e.textContent=msg;e.className='notice '+(error?'error':'success');clearTimeout(window._nt);window._nt=setTimeout(()=>e.classList.add('hidden'),5500);}
function loginError(msg){const e=$('loginError');e.textContent=msg;e.className='notice error';}
async function login(){const btn=$('loginBtn');btn.disabled=true;btn.textContent='Memproses...';$('loginInfo').textContent='Menghubungkan ke Supabase...';$('loginInfo').className='notice';try{const email=$('loginUser').value.trim(),pass=$('loginPass').value;if(!email||!pass)throw new Error('Email dan password wajib diisi.');if(!email.includes('@'))throw new Error('Masukkan email akun Supabase, bukan username.');saveSession(await authLogin(email,pass));await showAdmin();}catch(e){loginError('Login gagal: '+e.message);}finally{btn.disabled=false;btn.textContent='Masuk';$('loginInfo').className='notice hidden';}}
async function getSettings(){const d=await db('/site_settings?select=id,brand,username,logo_small,logo_large&id=eq.1');return d?.[0]||{id:1,...DEFAULTS,logo_small:'',logo_large:''};}
async function getProducts(){products=await db('/products?select=id,title,description,image,link,order_num,active&order=order_num.asc')||[];return products;}
function showPreview(imgId,emptyId,data){const img=$(imgId),empty=$(emptyId);if(data){img.src=data;img.classList.remove('hidden');empty.classList.add('hidden');}else{img.removeAttribute('src');img.classList.add('hidden');empty.classList.remove('hidden');}}
function renderList(){const list=$('adminList');$('totalStat').textContent=products.length;$('activeStat').textContent=products.filter(x=>x.active).length;$('inactiveStat').textContent=products.filter(x=>!x.active).length;$('productCount').textContent=products.length+' katalog';if(!products.length){list.innerHTML='<div class="empty">Belum ada katalog.</div>';return;}list.innerHTML=products.map((p,i)=>`<div class="admin-item"><div class="admin-item-img">${p.image?`<img src="${esc(p.image)}" alt="">`:'<span>W</span>'}</div><div class="admin-item-info"><b>${esc(p.title)}</b><small>${esc(p.description)}</small><em class="${p.active?'on':'off'}">${p.active?'Aktif':'Nonaktif'}</em></div><div class="admin-item-actions"><button data-edit="${i}">Edit</button><button data-toggle="${i}">${p.active?'Nonaktifkan':'Aktifkan'}</button><button class="danger" data-delete="${i}">Hapus</button></div></div>`).join('');list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openModal(products[+b.dataset.edit]));list.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggleProduct(products[+b.dataset.toggle]));list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteProduct(products[+b.dataset.delete]));}
function openModal(p=null){$('modalTitle').textContent=p?'Edit Katalog':'Tambah Katalog';$('editId').value=p?.id||'';$('fTitle').value=p?.title||'';$('fDesc').value=p?.description||'';$('fLink').value=p?.link||'';$('fOrder').value=p?.order_num??0;$('fActive').value=p?.active?1:0;currentProductImage=p?.image||'';showPreview('fImagePreview','fImageEmpty',currentProductImage);$('fImageFile').value='';$('modal').classList.remove('hidden');}
function closeModal(){$('modal').classList.add('hidden');}
async function toggleProduct(p){try{await db('/products?id=eq.'+encodeURIComponent(p.id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({active:!p.active})});await getProducts();renderList();notice('Status katalog diperbarui.');}catch(e){notice('Gagal mengubah status: '+e.message,true);}}
async function deleteProduct(p){if(!confirm('Hapus katalog ini?'))return;try{await db('/products?id=eq.'+encodeURIComponent(p.id),{method:'DELETE',headers:{Prefer:'return=minimal'}});await getProducts();renderList();notice('Katalog dihapus.');}catch(e){notice('Gagal menghapus: '+e.message,true);}}
function readAndResize(file,max=1200,quality=.82){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(!file.type.startsWith('image/'))return reject(new Error('File harus berupa gambar.'));const fr=new FileReader();fr.onerror=()=>reject(new Error('File foto tidak bisa dibaca.'));fr.onload=()=>{const im=new Image();im.onerror=()=>reject(new Error('Foto tidak valid atau rusak.'));im.onload=()=>{const scale=Math.min(1,max/Math.max(im.width,im.height));const w=Math.max(1,Math.round(im.width*scale)),h=Math.max(1,Math.round(im.height*scale));const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.drawImage(im,0,0,w,h);let out=c.toDataURL('image/webp',quality);if(!out.startsWith('data:image/webp'))out=c.toDataURL('image/jpeg',quality);resolve(out);};im.src=fr.result;};fr.readAsDataURL(file);});}
async function saveLogos(){const btn=$('saveLogos');btn.disabled=true;btn.textContent='Menyimpan...';try{const s=await getSettings();const payload={id:1,brand:s.brand||DEFAULTS.brand,username:s.username||'admin',logo_small:selectedSmall||s.logo_small||'',logo_large:selectedLarge||s.logo_large||''};await db('/site_settings?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});selectedSmall=payload.logo_small;selectedLarge=payload.logo_large;showPreview('smallLogoPreview','smallLogoEmpty',selectedSmall);showPreview('largeLogoPreview','largeLogoEmpty',selectedLarge);notice('Logo berhasil disimpan.');}catch(e){notice('Gagal menyimpan logo: '+e.message,true);}finally{btn.disabled=false;btn.textContent='Simpan Logo';}}
async function saveProduct(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='Menyimpan...';try{let image=currentProductImage;const f=$('fImageFile').files[0];if(f)image=await readAndResize(f,1200,.8);const id=$('editId').value||crypto.randomUUID();const item={id,title:$('fTitle').value.trim(),description:$('fDesc').value.trim(),image,link:$('fLink').value.trim(),order_num:Number($('fOrder').value)||0,active:$('fActive').value==='1'};if(!item.title||!item.link)throw new Error('Nama katalog dan link wajib diisi.');if($('editId').value)await db('/products?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(item)});else await db('/products',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(item)});closeModal();await getProducts();renderList();notice('Katalog berhasil disimpan.');}catch(e){notice('Gagal menyimpan katalog: '+e.message,true);}finally{btn.disabled=false;btn.textContent='Simpan Katalog';}}
async function showAdmin(){ $('loginView').classList.add('hidden');$('adminView').classList.remove('hidden');try{const s=await getSettings();selectedSmall=s.logo_small||'';selectedLarge=s.logo_large||'';showPreview('smallLogoPreview','smallLogoEmpty',selectedSmall);showPreview('largeLogoPreview','largeLogoEmpty',selectedLarge);await getProducts();renderList();}catch(e){notice('Gagal memuat panel: '+e.message,true);}}
function bind(){
 $('loginForm').addEventListener('submit',e=>{e.preventDefault();login();});
 $('logoutBtn').onclick=()=>{session=null;ls('witama_admin_session',null);ls('witama_admin_email',null);location.reload();};
 $('addBtn').onclick=()=>openModal();$('closeModal').onclick=closeModal;$('cancelBtn').onclick=closeModal;$('productForm').addEventListener('submit',saveProduct);$('saveLogos').onclick=saveLogos;
 $('smallLogoFile').onchange=async e=>{try{selectedSmall=await readAndResize(e.target.files[0],800,.86);showPreview('smallLogoPreview','smallLogoEmpty',selectedSmall);}catch(x){notice(x.message,true);e.target.value='';}};
 $('largeLogoFile').onchange=async e=>{try{selectedLarge=await readAndResize(e.target.files[0],1200,.84);showPreview('largeLogoPreview','largeLogoEmpty',selectedLarge);}catch(x){notice(x.message,true);e.target.value='';}};
 $('fImageFile').onchange=async e=>{try{currentProductImage=await readAndResize(e.target.files[0],1000,.8);showPreview('fImagePreview','fImageEmpty',currentProductImage);}catch(x){notice(x.message,true);e.target.value='';}};
}
(async()=>{bind();$('loginUser').value=ls('witama_admin_email')||'';if(await restoreSession())await showAdmin();})();
