const SB_URL="https://ozsfnvzqtizptxymtxzf.supabase.co";
const SB_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96c2ZudnpxdGl6cHR4eW10eHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEwNjIzMjksImV4cCI6MjEwNjYzODMyOX0.2TuFxRzKL4aHjRsFNyVsG3-LPn4UGre64NzhnT7W1Po";
const API=SB_URL+"/rest/v1";const FALLBACK=window.DEFAULT_PRODUCTS||[];
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
async function api(path){const r=await fetch(API+path,{headers:{apikey:SB_ANON_KEY}});if(!r.ok)throw new Error("HTTP "+r.status);return r.json();}
function setBrand(brand,smallLogo,largeLogo){document.title=brand+" — Katalog Digital";document.querySelector('meta[name=description]')?.setAttribute('content',brand+" — katalog produk dan layanan digital.");const b=document.getElementById("brandName");if(b)b.innerHTML=esc(brand).replace(/\s+(Store\.ID)$/i,' <i>$1</i>');const h=document.getElementById("heroBrandName");if(h)h.textContent=brand;const f=document.getElementById("footerBrand");if(f)f.textContent=brand;const nav=document.getElementById("navLogo");if(nav){nav.innerHTML=smallLogo?`<img src="${esc(smallLogo)}" alt="">`:`<span>${esc((brand||"W").trim().charAt(0)||"W")}</span>`;}const hero=document.getElementById("heroLogo"),empty=document.getElementById("heroLogoEmpty");if(hero&&empty){if(largeLogo){hero.src=largeLogo;hero.classList.remove("hidden");empty.classList.add("hidden");}else{hero.removeAttribute("src");hero.classList.add("hidden");empty.textContent=(brand||"W").trim().charAt(0)||"W";empty.classList.remove("hidden");}}const wp=document.getElementById("siteWallpaper");if(wp){if(largeLogo){wp.style.backgroundImage=`url("${String(largeLogo).replace(/"/g,'\\"')}")`;wp.classList.add("has-wallpaper");}else{wp.style.backgroundImage="none";wp.classList.remove("has-wallpaper");}}}
async function loadBrand(){try{const d=await api('/site_settings?select=brand,logo_small,logo_large&id=eq.1');const s=d?.[0];if(s)setBrand(s.brand||"Witama Store.ID",s.logo_small,s.logo_large);}catch(e){setBrand("Witama Store.ID","","");}}
function openDetail(p){const m=document.getElementById("detailModal");document.getElementById("detailTitle").textContent=p.title;document.getElementById("detailDesc").textContent=p.description||"Tidak ada deskripsi.";const img=document.getElementById("detailImage"),fallback=document.getElementById("detailImageFallback");if(p.image){img.src=p.image;img.classList.remove("hidden");fallback.classList.add("hidden");}else{img.removeAttribute("src");img.classList.add("hidden");fallback.classList.remove("hidden");}const open=document.getElementById("detailOpen");open.href=p.link||"#";m.classList.remove("hidden");document.body.style.overflow="hidden";}
function closeDetail(){document.getElementById("detailModal").classList.add("hidden");document.body.style.overflow="";}
async function render(){let list=[];try{list=await api('/products?select=id,title,description,image,link,order_num,active&active=eq.true&order=order_num.asc');}catch(e){}if(!list.length)list=FALLBACK.filter(x=>Number(x.active)===1).sort((a,b)=>(a.order||0)-(b.order||0));const grid=document.getElementById("productGrid"),empty=document.getElementById("empty");document.getElementById("count").textContent=`${list.length} produk`;grid.innerHTML=list.map((p,i)=>`<article class="product-card" style="--i:${i}" data-index="${i}">${p.image?`<img class="product-card-img" src="${esc(p.image)}" alt="${esc(p.title)}" loading="lazy">`:`<div class="product-placeholder">✦</div>`}<div class="product-info"><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p></div><div class="product-arrow">›</div></article>`).join("");grid.querySelectorAll(".product-card").forEach((el,i)=>el.addEventListener("click",()=>openDetail(list[i])));empty.classList.toggle("hidden",list.length!==0);grid.classList.toggle("hidden",list.length===0);}
document.getElementById("detailClose")?.addEventListener("click",closeDetail);document.getElementById("detailBack")?.addEventListener("click",closeDetail);document.getElementById("detailModal")?.addEventListener("click",e=>{if(e.target.id==="detailModal")closeDetail();});document.getElementById("navBack")?.addEventListener("click",()=>{if(history.length>1)history.back();else location.hash="#top";});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDetail();});loadBrand().finally(render);
